### ISSUE TITLE
Fatal: Internal error 2009112601

### ISSUE THREAD

**Issue by theavege** [circular17/DimPas#13]
This error (like [there](https://fpc-pascal.freepascal.narkive.com/SW4n6iDW/o2-internal-compiler-errors)) occurs when the [build](https://github.com/theavege/DimPas/actions/runs/12234010000/job/34122291345) mode is release.

**Comment by circular17** [comment]
Thanks for reporting it. Fixing this bug can be a way to try out the build checks.
